### ISSUE TITLE
[Feature Suggestion]: Is it possible to assign multiple possible items in one slot?

### ISSUE THREAD

**Issue by SpitlightMk2** [mehboss/CustomRecipes#41]
### What is your question?

As in vanilla Minecraft, one can craft 4 sticks with 2 pieces of wooden planks of any type (and they don't need to be the same type). Is it possible to define custom recipes like that with the plugin? If so, how should I configure the "Ingredients" in .yml file? If not, may I suggest that to be a new feature?

It is still possible to implement in current version(1.8.8) of CR by creating multiple recipe .yml files and list out all possibilities but the number of .yml files just blows up if more than one material slot accepts a random item from a certain list.

### Server Version

1.20.1

### Plugin Version

1.8.8

### Question Confirmation

- [X] I have checked the WIKI and the main page of the spigot resource, but still cannot find my answer.
- [X] I have provided sufficient information regarding my question.

**Comment by Valorless** [comment]
Like you said yourself, it is possible, but by making multiple recipe files.
Currently in 1.8.8, I do not think what you're looking for is possible, but you can definitely suggest it as a new feature :)

If I understand correctly, it's like you define your ingredients, but ingredient A (lets just call it A), can persist of any item on a list of items.
Like with a chest, we arrange it in a circle as usual, and W (being wood,) can be any wood from a list specified.

Ingredients Example of an Enchanting Table using multiple materials, but giving the same result:
```yml
ItemCrafting:
  - XBX
  - DOD
  - OOO
  
Ingredients:
  D:
    Material: DIAMOND
    Identifier: none
    Amount: 1
  B:
    Material: BOOK
    Identifier: none
    Amount: 1
  O:
    Material: 
      - OBSIDIAN
      - CRYING_OBSIDIAN
      - GILDED_BLACKSTONE
    Identifier: none
    Amount: 1
```
