### ISSUE TITLE
Add Furnace and Stonecutter options.

### ISSUE THREAD

**Issue by Poikilos** [mehboss/CustomRecipes#44]
### What is your suggestion?

I would like to be able to specify which "Converter" is necessary to create the output, so that the output would be from a Furnace or Stonecutter instead of a crafting table (or by hand).

### Can you show some examples?

- Either "Converter" (String), optionally, is "FURNACE" or "STONECUTTER". Otherwise, crafting is the means (if Converter is null, the recipe doesn't require either).
- Setting `Converter: STONECUTTER` would require MC 1.14, so that could be checked in RecipeManager.java when other version issues are checked.

### Beneficial to others?

Immersion: Some things that don't make sense to craft by hand but require a Furnace or Stonecutter could such as in that case be more immersive (suspending disbelief).

Balance: There are cases when an item being crafted with no barrier (in this case, no tech tier) is overpowered (disrupts balance more than if there were something required), such as, crafting it during combat or before placing any blocks.

Examples:
- Converting cobblestone to gravel. The Stonecutter doing it doesn't break the illusion like doing it by hand or the crafting table would.
  - [ ] STONECUTTER option needs to check API version, or show error if not 1.14
- Converting wheat seeds to sand. Doing so in the furnace it isn't realistic per se, but would make more sense than by hand and depends on a tech tier for balance.
  - Below I made the identifier WHEATSAND so that it can coexist with other sand recipe(s), but it produces the regular SAND Item as shown (stacks with Vanilla sand).
  - [x] `FURNACE` option as used below works in my `converters` branch.
```yaml
WheatSand:
  Enabled: true
  Shapeless: true
  Item: SAND
  Amount: 1
  Identifier: WHEATSAND
  Converter: FURNACE
  ItemCrafting:
  - WXX
  - XXX
  - XXX
  Ingredients:
    W:
      Material: WHEAT_SEEDS
      Identifier: none
      Amount: 1
  Item-Flags: []
  Attribute: []
  Disabled-Worlds: []
  Placeable: true
  Ignore-Model-Data: false
```

Make sure error is shown and recipe isn't added if Converter is FURNACE or STONECUTTER in the following cases:
- [ ] More than one `ItemCrafting` ingredient is specified
- [ ] If result `Amount` > 1
- [ ] If more than one Ingredient is defined in `Ingredients`
  - [ ] or ingredient `Amount` > 1.

### Server Version

1.19.2

### Server Mode

Offline Mode
