### ISSUE TITLE
item duplication/ dont consumed when crafting

### ISSUE THREAD

**Issue by TECHOPC** [mehboss/CustomRecipes#50]
### What happened?

itens in the 3x3 grid dont get used if the result craft is shift+clicked

### What was supposed to happen?

itens on 3x3 grid get consumed 
![Minecraft-1 8 9-2024-04-07-23-37-15](https://github.com/mehboss/CustomRecipes/assets/34199654/10f3e185-a513-4a3b-8bb0-939baab4b5fb)

### How do I reproduce this issue?

```bash
1.but any custom recipe in the grid
2.shift+click the output
3.done
...
```

### Relevant log output

```shell
[19:26:22 ERROR]: [CustomRecipes] ITEMSTOADD: 7
[19:26:30 ERROR]: [CustomRecipes] ITEMSTOADD: 7
[19:28:50 ERROR]: [CustomRecipes] ITEMSTOADD: 7

```

### Server Version

1.8.9 paper

### Plugin Version

CustomRecipes_1.4.jar

### Server Mode

Offline Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello,
Default config?

**Comment by TECHOPC** [comment]
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# CustomRecipe remastered by MehBoss                                                                #
# Version v1.9                                                                                      #
#                                                                                                   #        
# If you find a bug, send me a PM and it will be fixed! :)                                          #
#                                                                                                   #
# For MC 1.14+ add 'Custom-Model-Data: INT' to your recipe for utilization                          #
# For MC 1.12+ you can use attribute modifiers                                                      #
#                                                                                                   #  
# (!) SET TO 'none' OR COMPLETELY REMOVE IF ANY OF THESE MESSAGES ARE NOT WANTED (!)                #
#                                                                                                   #             
#    Enchant Strings:                                                                               #
# http://pastebin.com/AWtKQ5UH                                                                      #
#    Effects:                                                                                       #
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffect.html                      #
#    Attributes:                                                                                    #
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/Attribute.html                      #
#    Item Flags:                                                                                    #
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemFlag.html                       #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
firstLoad: false
Debug: false
Update-Check: true
Messages:
  Invalid-Args: '&cInvalid args! (use: /crecipe give <player> <recipename> [amount])'
  Invalid-Perms: '&cYou are not allowed to use this command!'
  No-Perm-Place: '&cNão pode colocar isso no chão!'
  Player-Not-Found: '&cERROR: player not found!'
  Recipe-Not-Found: '&cERROR: recipe not found!'
  Inventory-Full: '&cERROR: target''s inventory is full!'
  Give-Recipe: '&aSuccessfully given player item!'
  Reloading: '&cReloading.. please wait'
  Reload: '&aSuccessfully reloaded Custom Recipes with&c %recipes% &arecipes!'
action-bar:
  enabled: true
  message: '&4You are not allowed to craft this item!'
chat-message:
  enabled: true
  close-inventory: true
  message: '&cYou must be a donor to craft this recipe!'
add:
  Add-Recipe: '&cPlease type the display name of the recipe you would like to add!'
  Recipe-Capture: '&cCaptured desired new recipe name! Opening menu..'
  Title: '&e%recipe% (ADDING RECIPE)'
gui:
  Open-Sound: CLICK
  Open-Message: '&aOpening menu..'
  Displayname: '&cRecipe Manager - Page %page%'

**Comment by TECHOPC** [comment]
```
PedregulhoCompactado:
  Enabled: true
  Shapeless: false
  Item: cobblestone
  Item-Damage: none
  Amount: 1
  Placeable: false
  Ignore-Data: false
  Ignore-Model-Data: false
  Custom-Tagged: true
  Durability: '100'
  Identifier: PedregulhoCompactado
  Converter: none
  Permission: crecipe.recipe.PedregulhoCompactado
  Name: '&8&lPedregulho Compactado'
  Lore:
  - '&3&l9x Pedregulho'
  - '&1&lIncomun'
  Hide-Enchants: true
  Enchantments:
  - DURABILITY:300
  ItemCrafting:
  - CCC
  - CCC
  - CCC
  Ingredients:
    C:
      Material: cobblestone
      Identifier: none
      Amount: 1
  Custom-Tags: []
  Item-Flags: []
  Attribute: []
  Custom-Model-Data: none
  Disabled-Worlds: []
```
