### ISSUE TITLE
Shift-click deletes cursor's itemstack if is same item as recipe output

### ISSUE THREAD

**Issue by Poikilos** [mehboss/CustomRecipes#55]
### What happened?

When using shift-click, and when cursor stack has same item, the cursor stack gets deleted and replaced with the quantity able to be crafted.

### What was supposed to happen?

Add (not replace) output items to cursor stack if same item. Any remaining (or different item) are dumped to inventory, or the ground as a last resort.

### How do I reproduce this issue?

```bash
1. Place input item in crafting grid
2. Hold some number of the output item (in cursor stack)
3. Shift-click on output item
```

The count that you keep is added to inventory (the count shown in error in the log below) but the count in the cursor stack is deleted.

I am using online mode but a local instance of Paper on Linux, so basically the same as testing on a server.

These steps reproduce the issue with reported Nov 1, 2023 (Version 1.8.8) by Dranty on <https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/reviews#review-511763-1701880>

- [ ] So if issue gets fixed, maybe comment there with this link and mention the issue is closed.

### Relevant log output

```shell
[08:49:08 ERROR]: [CustomRecipes] ITEMSTOADD: 14
```

### Server Version

Paper 1.20.4

### Plugin Version

1.9.1

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

Example cobblestone to gravel recipe (Gravel.yml):
```yaml
Gravel:
  Enabled: true
  Shapeless: true
  Item: GRAVEL
  Amount: 1
  Identifier: GRAVEL
  ItemCrafting:
  - CXX
  - XXX
  - XXX
  Ingredients:
    C:
      Material: COBBLESTONE
      Identifier: none
      Amount: 2
  Placeable: true
  Ignore-Model-Data: false
  Item-Flags: []
  Disabled-Worlds: []
```

Config.yml:
```yaml
Debug: false
Update-Check: true
Messages:
  Invalid-Args: '&cInvalid args! (use: /crecipe give <player> <recipename> [amount])'
  Invalid-Perms: '&cYou are not allowed to use this command!'
  No-Perm-Place: '&cYou cannot place an unplaceable block!'
  Player-Not-Found: '&cERROR: player not found!'
  Recipe-Not-Found: '&cERROR: recipe not found!'
  Inventory-Full: '&cERROR: target''s inventory is full!'
  Give-Recipe: '&aSuccessfully given player item!'
  Reloading: '&cReloading.. please wait'
  Reload: '&aSuccessfully reloaded Custom Recipes with&c %recipes% &arecipes!'
action-bar:
  enabled: true
  message: '&4You are not allowed to craft this item!'
chat-message:
  enabled: true
  close-inventory: true
  message: '&cYou don''t have permission to craft this recipe!'
add:
  Add-Recipe: '&cPlease type the display name of the recipe you would like to add!'
  Recipe-Capture: '&cCaptured desired new recipe name! Opening menu..'
  Title: '&e%recipe% (ADDING RECIPE)'
gui:
  Open-Sound: CLICK
  Open-Message: '&aOpening menu..'
  Displayname: '&cRecipe Manager - Page %page%'
firstLoad: false
```
