### ISSUE TITLE
[Feature Request]: Unplaceable items 

### ISSUE THREAD

**Issue by MummieSenpai** [mehboss/CustomRecipes#8]
as you make some custom items would be nice to have an option in the config or a new config for blacklisting/whitelisting crafting recipe items.

for example if you make a special item with the plugin a block or an item like a chest or a torch that is used in a multi craft recipe and a player places it it loses all data if we could prevent  this it would keep data .

example config could be 

Name:
```yml

 #Message Displayed to Player When They Try Place An Unplaceable Block
  No_Perm_Place: '&4You Cannot Place an Unplaceable Block!'


#List of Names Which, When On a Block, Cannot Be Placed
- 'example text'

#List of Lore Which, When On a Block, Cannot Be Placed
Lore:
- 'example text'
```

or if in recipe config an extra line 
`placeable: false`
